#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.45.66.142:10136/renren-fast?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: dvp
#      password: 123456
#      initial-size: 10
#      max-active: 100
#      min-idle: 10
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      #Oracle需要打开注释
#      #validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        #login-username: admin
#        #login-password: admin
#      filter:
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: false
#        wall:
#          config:
#            multi-statement-allow: true
#
#web:
#  upload-path: C:\workspace\renren-fast\renren-fast\storage
#
##多数据源的配置
#dynamic:
#  datasource:
#    renren:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.45.66.142:10136/renren-fast?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: dvp
#      password: 123456
#    huzheng:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.45.66.142:10136/zzdj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: zzdj
#      password: zzdj3260235
#    jianghai:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.45.66.142:10136/zzdj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: zzdj
#      password: zzdj3260235
#    kaiping:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.45.66.142:10136/zzdj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: zzdj
#      password: zzdj3260235
#    voyage:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.45.66.142:10136/zzdj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: zzdj
#      password: zzdj3260235