server:
  port: 8080
#  servlet:
#    context-path: /springboot-security

spring:
  application:
    name: springboot-security
  thymeleaf:
    cache: false
#  mvc:
#    view:
#      prefix: /WEB-INF/views
#      suffix: .jsp


