server:
  port: 8001

spring:
  application:
    name: provider1
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: org.ohx.provider8001.entity
#  global-config:
#    #数据库相关配置
#    db-config:
#      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: AUTO
#      logic-delete-value: -1
#      logic-not-delete-value: 0
#    banner: false
#    #原生配置
#    configuration:
#      map-underscore-to-camel-case: true
#      cache-enabled: false
#      call-setters-on-nulls: true
#      jdbc-type-for-null: 'null'
#      default-executor-type: simple