spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

#设置feign客户端的超时时间，通过ribbon设置（默认1秒）
ribbon:
  #指的是建立连接后从服务端读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么spring日志级别监控哪个接口
    org.ohx.consumer.service.FeignService: debug