eureka:
  instance:
    #eureka服务端实例名称
    hostname: eureka7002
  server:
    #关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位毫秒
    eviction-interval-timer-in-ms: 90000
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，职责是维护服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #单机指向自己
      #defaultZone: http://localhost:7002/eureka/
      #集群指向其他eureka
      defaultZone: http://localhost:7001/eureka/